apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:bYWxcQoQ+2lkGUpEkMA+mcNJoPyl9oiZqw6LUSH5cghB1ki9HMa0eMcC1CDdUL73cNUeI3q9/DTodPjgRy/Fhdj29j/rcbt1FIRdcozYEKbpMJsxLizS592vBpdg4NMylmwWTV4SBtsIiIABmAQGZd/z9j+GHjsbFaWLMD2GJPr4FBsdGZsz0Z8reFVXQxTa43/ijjlLOC2SEB3JV3pVA1WskRBjRdMq+fGPwJm6sfiWr/oFY+3LwDkNAjaJTDA0UUGth8k7ReTWZS8cl7W1vWJK2DG2z9ZkjDpIlyiHUW/JzR70Wv03ih2zeiU=,iv:vjsWYnEdaGb6XLNIGQ6HpbJDXXitHDERatOWMkHma3s=,tag:Vtite+yWOebTJSSDeSO/Yg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeE5seXlwaTBLSWpTekUr
            b2R3V2xPMnF3eEwyVU5kVHhLR3BLQ3dnSzEwCld0RzVtMU9yVWgvR3FWMS9WenZB
            MjFhMFJIRVd6OUZIRWFLYTdrc1FXcFkKLS0tIHRacVkxeDluVFRzWSsxM21WK1BV
            Q1ZWb3IyanJyNC9aa0NPRHhCOVk0YTgKWiTWi5M9g1SIhDLqTSs/NsjSSo22BlYA
            KhzcJ+N6/Ab3MM0XMpzRsKN4GQRyd0CF1rtK2ba3hMUYcQpKCsXXIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gdhq52al32unj025af3sk04zc9qeg8xgprhzmw4pxdzwdu4gqa0qgt6cjy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T15:06:44Z"
    mac: ENC[AES256_GCM,data:sDcbXbp6sNoiF1qLjTYO+GgX32vqfeB/xvJl/xzCm84jrFAcJbsUeV1KUCjwE/EVsQRDvFx5pUqIK21JIWLkA2UvZoyxRVGx9wXTLwART9W1cdmcrACitJXfJynbCsmBLA5RAaPD3KZp7CXaHbLVoLwK5smR0EvmtjHTjdE5dmg=,iv:b/Uq3YKLiQYEvoGKrTwz9QPG3XUtqp5/DqGOX6V1kWE=,tag:fZuON6lYOgVwzbyWU/Js3w==,type:str]
    version: 3.13.2
