apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiODMwMDk4MDg3Y2JiNTQ4NjZmZDkxOTBlMTc1ODgxNDIiLCJUdW5uZWxTZWNyZXQiOiIvczZPdll2dmw1VTZ6a3UvU1ErYnprK0VmS3g3NGRHRmJEUWJNd2hCektvPSIsIlR1bm5lbElEIjoiMGM0NTBlZjUtOTg0NS00MTAwLWFjOGMtMTNlNzU4NTE5Mjc3IiwiRW5kcG9pbnQiOiIifQ==
kind: Secret
metadata:
  name: tunnel-credentials
